title: Tasty Typography
description: A blog exploring the world of typography
header_text: Lily's Blogs
footer_text: Copyright 2020 Lily Taylor
header_feature_image: ../uploads/pages.jpg
bannerheight: 20vmax
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
