title: Tasty Typography
description: A blog exploring the world of typography
header_text: ""
footer_text: Copyright 2020 Lily Taylor
header_feature_image: ../uploads/323eb438-8b92-4991-9c48-c15139c396b6.png
bannerheight: 20vmax
logo: ../uploads/logo.png
favicon: ../uploads/logo.png
gridlayout: true
fixednavbar: false
upzoom: true
items:
  - siteurl: /aboutme
    name: Portfolio
    tab: true
