title: Tasty Typography
description: A blog exploring the world of typography
header_text: Lily's Blogs
footer_text: Copyright 2020 Lily Taylor
header_feature_image: ../uploads/straw-7.jpg
bannerheight: 20vmax
logo: ../uploads/ttred.png
favicon: ../uploads/ttred.png
gridlayout: false
fixednavbar: false
upzoom: true
